- hosts: web
  tasks:
    - name: Install httpd
      become: true
      yum:
       name: httpd
       state: present
    - name: Copy index.html
      become: true
      copy:
       src: "tmp/index.html"
       dest: "/var/www/html/index.html"
    - name: Start httpd service
      become: true
      service:
       name: httpd
       state: "started"